name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${mainPackage}.${name}
version: ${version}
api-version: 1.14

softdepend:
  - PlaceholderAPI

commands:
  eb:
    description: Toggles the Exploding Blocks plugin
    aliases:
      - explodingblocks
    permission: eb.toggle

permissions:
  eb.toggle:
    description: Allows the player to use /eb
