name: Publish
on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  publish:
    uses: srnyx/tools/.github/workflows/publish.yml@main
    with:
      versions: ">=1.14.3"
      modrinth: kKXUJTU9
      curseforge: 896921
    secrets: inherit
